"""company email pattern

Revision ID: bac8bcce3879
Revises: bc6aa5a4698c
Create Date: 2026-09-04 20:29:19.820477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac8bcce3879'
down_revision: Union[str, Sequence[str], None] = 'bc6aa5a4698c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_pattern', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('catch_all', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pattern_checked_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('pattern_checked_at')
        batch_op.drop_column('catch_all')
        batch_op.drop_column('email_pattern')

    # ### end Alembic commands ###
