"""initial schema

Revision ID: bc6aa5a4698c
Revises: 
Create Date: 2026-09-04 08:57:28.600707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6aa5a4698c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_health',
    sa.Column('adapter', sa.String(length=40), nullable=False),
    sa.Column('last_ok_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('calls_today', sa.Integer(), nullable=False),
    sa.Column('calls_date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('adapter')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('ats_type', sa.String(length=40), nullable=True),
    sa.Column('ats_board_token', sa.String(length=255), nullable=True),
    sa.Column('main_phone', sa.String(length=60), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_normalized_name'), ['normalized_name'], unique=True)

    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_kind'), ['kind'], unique=False)

    op.create_table('postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('normalized_title', sa.String(length=300), nullable=False),
    sa.Column('seniority', sa.String(length=20), nullable=True),
    sa.Column('location_raw', sa.String(length=300), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('remote_type', sa.String(length=10), nullable=False),
    sa.Column('remote_scope', sa.String(length=60), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=False),
    sa.Column('description_complete', sa.Boolean(), nullable=False),
    sa.Column('salary_raw', sa.String(length=200), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('apply_url', sa.String(length=1000), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prefilter_result', sa.JSON(), nullable=True),
    sa.Column('dismiss_reason', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_postings_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postings_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_postings_dedupe_key'), ['dedupe_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_postings_normalized_title'), ['normalized_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_postings_status'), ['status'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=60), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_posting_id'), ['posting_id'], unique=False)

    op.create_table('contact_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credits', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_runs_posting_id'), ['posting_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('role_kind', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_status', sa.String(length=20), nullable=False),
    sa.Column('email_source', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('phone_kind', sa.String(length=20), nullable=True),
    sa.Column('phone_source', sa.String(length=40), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_posting_id'), ['posting_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('format', sa.String(length=5), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('ats_report', sa.JSON(), nullable=False),
    sa.Column('truth_check', sa.JSON(), nullable=False),
    sa.Column('change_log', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_posting_id'), ['posting_id'], unique=False)

    op.create_table('pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('close_reason', sa.String(length=20), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('posting_id')
    )
    with op.batch_alter_table('pipeline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_stage'), ['stage'], unique=False)

    op.create_table('posting_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_source_id')
    )
    with op.batch_alter_table('posting_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posting_sources_posting_id'), ['posting_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('missing_requirements', sa.JSON(), nullable=False),
    sa.Column('seniority_match', sa.String(length=10), nullable=False),
    sa.Column('eligibility', sa.JSON(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('one_line_summary', sa.String(length=300), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_posting_id'), ['posting_id'], unique=False)

    op.create_table('spend_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('usd_estimate', sa.Float(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spend_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spend_ledger_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_ledger_provider'), ['provider'], unique=False)

    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drafts_posting_id'), ['posting_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafts_posting_id'))

    op.drop_table('drafts')
    with op.batch_alter_table('spend_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spend_ledger_provider'))
        batch_op.drop_index(batch_op.f('ix_spend_ledger_occurred_at'))

    op.drop_table('spend_ledger')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_posting_id'))

    op.drop_table('scores')
    with op.batch_alter_table('posting_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posting_sources_posting_id'))

    op.drop_table('posting_sources')
    with op.batch_alter_table('pipeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_stage'))

    op.drop_table('pipeline')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_posting_id'))

    op.drop_table('documents')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_posting_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_company_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('contact_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_runs_posting_id'))

    op.drop_table('contact_runs')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_posting_id'))

    op.drop_table('activities')
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postings_status'))
        batch_op.drop_index(batch_op.f('ix_postings_normalized_title'))
        batch_op.drop_index(batch_op.f('ix_postings_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_postings_country'))
        batch_op.drop_index(batch_op.f('ix_postings_company_id'))

    op.drop_table('postings')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_kind'))

    op.drop_table('runs')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_normalized_name'))

    op.drop_table('companies')
    op.drop_table('adapter_health')
    # ### end Alembic commands ###
